In [140]:
import numpy as np

# Create a 1D NumPy Array

In [141]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [142]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


# Inspection and Properties

In [143]:
print("Shape: ", temperatures_w1.shape)

Shape:  (7,)


In [144]:
print("Data type: ",temperatures_w1.dtype)

Data type:  float64


In [145]:
print("No of elements: ",temperatures_w1.size)

No of elements:  7


# Array Operations

In [146]:
temp_f = (temperatures_w1 * 9/5)+32

In [147]:
print("Temperature in farenheit: ",temp_f)

Temperature in farenheit:  [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [148]:
print("Max temperature: ",temperatures_w1.max())

Max temperature:  26.1


In [149]:
print("Min temperature: ",temperatures_w1.min())

Min temperature:  20.8


In [150]:
print("Mean temperature for the week: ",round(temperatures_w1.mean(),2))

Mean temperature for the week:  23.54


# Array Slicing and Indexing

In [151]:
print("Temperature for first 3 days of the week: ",temperatures_w1[:3])

Temperature for first 3 days of the week:  [22.5 25.3 20.8]


In [152]:
print("Temperatures for the weekend (last two days): ",temperatures_w1[-2:])

Temperatures for the weekend (last two days):  [24.8 21.9]


In [153]:
print("Temperatures for the middle three days of the week: ",temperatures_w1[2:5])

Temperatures for the middle three days of the week:  [20.8 23.4 26.1]


# Create a 2D Array

In [154]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [155]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


# Inspect and Slice the 2D Array

In [156]:
print("Shape: ",temperatures.shape)

Shape:  (2, 7)


In [157]:
print("Data type: ",temperatures.dtype)

Data type:  float64


In [158]:
print("Total number of elements in the temperatures array: ",temperatures.size)

Total number of elements in the temperatures array:  14


In [159]:
week1 = temperatures[0]
print("Week 1 temperatures: ",week1)

Week 1 temperatures:  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [160]:
week2 = temperatures[1]
print("Week 2 temperatures: ",week2)

Week 2 temperatures:  [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [161]:
print("Week 1 weekend temperatures: ",temperatures[0,-2:])

Week 1 weekend temperatures:  [24.8 21.9]


In [162]:
print("Week 2 weekend temperatures: ",temperatures[1,-2:])

Week 2 weekend temperatures:  [22.8 20.1]


# Pandas Series

In [163]:
import pandas as pd

# Creating Pandas Series

In [164]:
Marks = pd.Series([95, 92, 89, 85, 80],index =['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

In [165]:
print(Marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


# Indexing and Slicing

In [166]:
print("Mark of the 1st rank student using the integer index position: ",Marks.iloc[0])

Mark of the 1st rank student using the integer index position:  95


In [167]:
print("Marks of the top 3 ranks by specifying their index labels: ",Marks.loc[['Rank1','Rank2','Rank3']])

Marks of the top 3 ranks by specifying their index labels:  Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [168]:
print("Mark of the 3rd rank student using iloc: ",Marks.iloc[2])

Mark of the 3rd rank student using iloc:  89


In [169]:
print("Ranks where the marks are greater than 90: ",Marks[Marks>90])

Ranks where the marks are greater than 90:  Rank1    95
Rank2    92
dtype: int64


# Manipulating Series

In [170]:
Marks.loc['Rank1']=100

In [171]:
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [172]:
Marks.drop('Rank5')

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [173]:
cgpa =Marks/10

In [174]:
print("CGPA: ",cgpa)

CGPA:  Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64


# Pandas DataFrame

# Creating Pandas DataFrame

In [175]:
transactions =pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 
                    'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Data Exploration

In [176]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [177]:
print("Head: ",transactions.head())

Head:     TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [178]:
print("Tail: ",transactions.tail())

Tail:     TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [179]:
print("Shape: ",transactions.shape)

Shape:  (10, 4)


In [180]:
print("Columns: ",transactions.columns)

Columns:  Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')


In [181]:
print("Data type: ",transactions.dtypes)

Data type:  TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object


In [182]:
print("Product Category and Amount \n ")
print(transactions[['ProductCategory', 'Amount']])

Product Category and Amount 
 
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [183]:
print("Last 3 columns \n")
print(transactions.iloc[:,-3:])

Last 3 columns 

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [184]:
f = transactions[(transactions['Region']=='North')&(transactions['Amount']>200)]
print(f)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [185]:
print("Value counts \n")
print(transactions['ProductCategory'].value_counts())

Value counts 

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [186]:
print("Unique values in Region \n ")
print(transactions['Region'].unique())

Unique values in Region 
 
<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [187]:
print("Mean amount for each region \n ")
print(transactions.groupby ('Region')['Amount'].mean())

Mean amount for each region 
 
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


# Manipulating the DataFrame

In [188]:
transactions.loc[transactions['TransactionID']==102,
   'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [194]:
transactions['Discount']=transactions['Amount']*0.1
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [195]:
transactions[transactions['TransactionID'] != 109]

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [196]:
transactions = transactions.drop(columns='Discount')
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
